name = "TestContexts"
uuid = "bc03c374-6515-4bc9-983b-02908b112166"
authors = ["Oren Ben-Kiki <oren@ben-kiki.org>"]
version = "0.1.0"

[compat]
julia = "1.6"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
